version: 2

before:
  hooks:
  # You may remove this if you don't use go modules.
  - go mod tidy

builds:
- id: tsukatsuki
  binary: tsukatsuki
  main: ./main.go
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64

archives:
- formats: [ tar.gz ]
  name_template: >-
    {{ .ProjectName }}_{{ .Version }}_{{ title .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}


nfpms:
- id: deb
  ids:
  - tsukatsuki
  package_name: tsukatsuki
  vendor: alieexe
  homepage: https://github.com/aLieexe/tsukatsuki
  maintainer: aLieexe <rizky.alay@gmail.com>
  description: Command-line tool designed to simplify application deployment on self-hosted infrastructure
  license: MIT

  formats:
  - deb

  section: utils
  priority: optional
  bindir: /usr/bin

  dependencies:
  - python3

  contents:
  - src: README.md
    dst: /usr/share/doc/tsukatsuki/README.md

changelog:
  sort: asc
  filters:
    include:
    - '^feat:'
    - '^fix:'
    - '^chore:'
    - '^refactor:'
    - '^perf:'
    - '^build:'

checksum:
  name_template: "checksums.txt"

